---
# Update all packages to the latest version
- apt: update_cache=yes

- name: install packages
  apt: name={{ item }} state=present
  with_items:
      - lldpd
      - wget
      - curl
      - iptraf
      - tcpdump

# install lldp daemon start option file
- name: install lldpd config
  template: src=lldpd.j2 dest=/etc/default/lldpd


# start lldpd daemon
- command: /etc/init.d/lldpd start
  

