---
# Update all packages to the latest version
- apt: update_cache=yes

- name: install packages
  apt: name={{ item }} state=present
  with_items:
      - lldpd
      - wget
      - curl
      - iptraf
      - tcpdump

# start lldpd daemon
- command: /etc/init.d/lldpd start
  

